# Generated by Django 5.0.4 on 2026-08-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workouts', to='workouts.exercise'),
        ),
    ]
