# Generated by Django 5.0.4 on 2026-06-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_workoutset'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
    ]
